pipeline {
  agent {
  docker {
    image 'sreya1215/maven-docker-agent:latest'
    args '--user root -v /var/run/docker.sock:/var/run/docker.sock'
  }
}
  environment {
    SONAR_URL = "http://54.227.5.227:9000"
    GIT_REPO_NAME = "Jenkins-Zero-To-Hero"
    GIT_USER_NAME = "sreyajanjanam"
    DOCKER_IMAGE = "sreya1215/ultimate-cicd:${BUILD_NUMBER}"
  }

  stages {

    stage('Checkout') {
      steps {
        git branch: 'main', url: 'https://github.com/sreyajanjanam/Jenkins-Zero-To-Hero.git'
      }
    }

    stage('Build and Test') {
      steps {
        sh '''
          cd java-maven-sonar-argocd-helm-k8s/spring-boot-app
          mvn clean package
        '''
      }
    }

    stage('Prepare Environment') {
      steps {
        sh '''
          rm -rf /root/.sonar/cache/*
          rm -rf /root/.m2/repository/*
        '''
      }
    }

    stage('Static Code Analysis') {
      steps {
        withCredentials([string(credentialsId: 'sonarqube', variable: 'SONAR_AUTH_TOKEN')]) {
          sh '''
            cd java-maven-sonar-argocd-helm-k8s/spring-boot-app
            mvn sonar:sonar \
              -Dsonar.host.url=${SONAR_URL} \
              -Dsonar.login=${SONAR_AUTH_TOKEN} \
              -Dsonar.projectKey=spring-boot-app \
              -Dsonar.plugins.downloadOnlyRequired=true
          '''
        }
      }
    }

    stage('Build and Push Docker Image') {
      steps {
        script {
          def dockerImage = docker.image("${DOCKER_IMAGE}")
          docker.withRegistry('https://index.docker.io/v1/', "docker-cred") {
            sh '''
              cd java-maven-sonar-argocd-helm-k8s/spring-boot-app
              docker build -t ${DOCKER_IMAGE} .
            '''
            dockerImage.push()
          }
        }
      }
    }

    stage('Update Deployment File') {
      agent { label 'master' } // Run this part on Jenkins host, not inside container
      steps {
        withCredentials([string(credentialsId: 'github', variable: 'GITHUB_TOKEN')]) {
          sh '''
            git config user.email "lakshmisreyajanjanam@gmail.com"
            git config user.name "sreyajanjanam"
            sed -i "s/replaceImageTag/${BUILD_NUMBER}/g" java-maven-sonar-argocd-helm-k8s/spring-boot-app-manifests/deployment.yml
            git add java-maven-sonar-argocd-helm-k8s/spring-boot-app-manifests/deployment.yml
            git commit -m "Update deployment image to version ${BUILD_NUMBER}"
            git push https://${GITHUB_TOKEN}@github.com/${GIT_USER_NAME}/${GIT_REPO_NAME} HEAD:main
          '''
        }
      }
    }

  }
}
