pipeline {
  agent {
    docker {
      image 'maven:3.9.9-eclipse-temurin-17'  // Maven + Java 17
      args '--user root -v /var/run/docker.sock:/var/run/docker.sock'
    }
  }

  stages {

    stage('Checkout') {
      steps {
        git branch: 'main', url: 'https://github.com/sreyajanjanam/Jenkins-Zero-To-Hero.git'
      }
    }

    stage('Build and Test') {
      steps {
        sh '''
          cd java-maven-sonar-argocd-helm-k8s/spring-boot-app
          mvn clean package
        '''
      }
    }

    stage('Prepare Environment') {
      steps {
        // Clean up caches to prevent "No space left on device"
        sh '''
          rm -rf /root/.sonar/cache/*
          rm -rf /root/.m2/repository/*
        '''
      }
    }

    stage('Static Code Analysis') {
      environ
